# Generated by Django 5.1.3 on 2024-12-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("tempmax", models.FloatField()),
                ("tempmin", models.FloatField()),
                ("temp", models.FloatField()),
                ("conditions", models.CharField(max_length=255)),
                ("precip", models.FloatField()),
                ("precipprob", models.FloatField()),
                ("will_it_rain", models.BooleanField()),
                ("chance_of_rain", models.FloatField()),
                ("will_it_snow", models.BooleanField()),
                ("chance_of_snow", models.FloatField()),
                ("windspeed", models.FloatField()),
                ("windgust", models.FloatField()),
                ("winddir", models.FloatField()),
                ("humidity", models.FloatField()),
                ("pressure", models.FloatField()),
                ("dew", models.FloatField()),
                ("feelslike", models.FloatField()),
                ("cloudcover", models.FloatField()),
                ("visibility", models.FloatField()),
                ("uvindex", models.IntegerField()),
                ("sunrise", models.TimeField()),
                ("sunset", models.TimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecast.location",
                    ),
                ),
            ],
        ),
    ]
