# Generated by Django 5.1.3 on 2024-12-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherdata",
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
            },
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="cloudcover",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="dew",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="feelslike",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="precip",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="precipprob",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="temp",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="tempmax",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="tempmin",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="uvindex",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="winddir",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="windgust",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="windspeed",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="cloud_cover",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="dew_point",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="feels_like",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precipitation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precipitation_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="uv_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_direction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_gust",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="chance_of_rain",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="chance_of_snow",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="conditions",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_data",
                to="forecast.location",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="sunrise",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="sunset",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="visibility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="will_it_rain",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="will_it_snow",
            field=models.BooleanField(default=False),
        ),
    ]
