# Generated by Django 5.1.3 on 2024-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0004_weatherdata_chance_of_rain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="cloud_cover",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="conditions",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="dew_point",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="feels_like",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precipitation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precipitation_probability",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="sunrise",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="sunset",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="uv_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="visibility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_direction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_gust",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
