# Generated by Django 5.1.3 on 2024-12-06 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0005_weatherdata_cloud_cover_weatherdata_conditions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="wind_direction",
        ),
    ]
