# Generated by Django 5.1.3 on 2024-12-09 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0006_remove_weatherdata_wind_direction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherdata",
            options={
                "verbose_name": "WeatherData",
                "verbose_name_plural": "WeatherData",
            },
        ),
        migrations.RemoveField(
            model_name="location",
            name="country",
        ),
    ]
