# Generated by Django 5.1.3 on 2024-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="User ID")),
                ("chat_id", models.IntegerField(verbose_name="Chat ID")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Joined"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat_id", "user_id", "username"),
                        name="unique_chat_user",
                    )
                ],
            },
        ),
    ]
