# Generated by Django 5.1.3 on 2024-12-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0007_alter_weatherdata_options_remove_location_country"),
        ("notifications", "0002_remove_botuser_id_alter_botuser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="locations",
            field=models.ManyToManyField(related_name="users", to="forecast.location"),
        ),
    ]
